### ISSUE TITLE
weekly meeting(8/24)

### ISSUE THREAD

**Issue by sweetcocoa** [LSTMTUT/Main-Issue#6]
Time : 24th August, 9PM (KST)
Google Presentation + Hangout
Meeting URL: https://hangouts.google.com/call/6zwvqqqjp5hilanopqm45kuvqqe

Presenters: 최종호 + (Please Update) + 조재민
Contents: 
최종호 https://docs.google.com/presentation/d/1D9DOvv1NAdiIE2Kc_zTQhXx9LRlcD1Qp_yhvY_JihS8/edit?usp=sharing

**Comment by maestrojeong** [comment]
[3rd study.pdf](https://github.com/LSTMTUT/Main-Issue/files/434563/3rd.study.pdf)
